# Anna Clara de Andrada

## Is there a relationship between the decrease in forest coverage and the increase in threatened species?
It is my personal interest to explore this question further as it is imperative to understand the factors that contribute to climate change and biodiversity loss if we want to foster a sustainable future.

In [ ]:
import numpy as np
import pandas as pd

df1 = pd.read_csv('Carbon Dioxide Emission Estimates.csv')
df2 = pd.read_csv('Threatened Species.csv')
df3 = pd.read_csv('Land.csv')
df4 = pd.read_csv('Water and Sanitation Services.csv')

print(df1)
print(df2)
print(df3)
print(df4)

     CO2 emission estimates  Year  \
0                   Albania  1975   
1                   Albania  1985   
2                   Albania  1995   
3                   Albania  2005   
4                   Albania  2010   
...                     ...   ...   
2127               Zimbabwe  2005   
2128               Zimbabwe  2010   
2129               Zimbabwe  2015   
2130               Zimbabwe  2016   
2131               Zimbabwe  2017   

                                                 Series     Value  
0     Emissions (thousand metric tons of carbon diox...  4338.334  
1     Emissions (thousand metric tons of carbon diox...  6929.926  
2     Emissions (thousand metric tons of carbon diox...  1848.549  
3     Emissions (thousand metric tons of carbon diox...  3825.184  
4     Emissions (thousand metric tons of carbon diox...  3930.295  
...                                                 ...       ...  
2127  Emissions per capita (metric tons of carbon di...     0.794  
2128  Emiss

In [ ]:
import matplotlib.pylab as plt
import seaborn as sns

#for my question, I will be looking at only 2 datasets, df3 & df2
number_of_rows_and_columns = df2.shape
first_five_rows = df2.head()
column_names = df2.columns

number_of_rows_and_columns2 = df3.shape
first_five_rows2 = df3.head()
column_names2 = df3.columns


print(number_of_rows_and_columns)
print(first_five_rows)
print(column_names)

print(number_of_rows_and_columns2)
print(first_five_rows2)
print(column_names2)

'''running this analysis helped me understand that the # of rows are similar in both datasets, 
and they are organized in the same manner when we look at the column names as well as the first 5 rows of data. 
this analysis also shed light onto the fact that the columns labeled 'land' and 'threatened species' both contain 
"country" data. This means that these columns will have to be renamed to the same name when the 
datasets are merged. 

Furthermore, by looking at the first few rows, I noticed that the Land Dataset contains different series, for which 
I will only use one (Land area) to answer my research question, so I will have to "drop" the other rows.

'''


(6918, 4)
  Threatened species  Year                                    Series  Value
0        Afghanistan  2004  Threatened Species: Vertebrates (number)     31
1        Afghanistan  2010  Threatened Species: Vertebrates (number)     31
2        Afghanistan  2016  Threatened Species: Vertebrates (number)     35
3        Afghanistan  2017  Threatened Species: Vertebrates (number)     35
4        Afghanistan  2018  Threatened Species: Vertebrates (number)     34
Index(['Threatened species', 'Year', 'Series', 'Value'], dtype='object')
(6159, 4)
                            Land  Year                               Series  \
0  Total, all countries or areas  2005        Land area (thousand hectares)   
1  Total, all countries or areas  2005      Arable land (thousand hectares)   
2  Total, all countries or areas  2005  Permanent crops (thousand hectares)   
3  Total, all countries or areas  2005     Forest cover (thousand hectares)   
4  Total, all countries or areas  2005   Arable land (% 

In [ ]:
unique_values = df2.nunique(axis=0)
print(unique_values)

'''this analysis showcased that simililarly to the "Land" dataset, "Threatened Species" also 
contains different variable under the "series" column, so we will have to be mindful of that when 
analyzing and interpreting the data''' 

Threatened species    253
Year                    7
Series                  4
Value                 613
dtype: int64


'this analysis showcased that simililarly to the "Land" dataset, "Threatened Species" also \ncontains different variable under the "series" column, so we will have to be mindful of that when \nanalyzing and interpreting the data'

In [ ]:
print(df2['Series'].unique())

''' to show the unique values under the 'series' column '''

['Threatened Species: Vertebrates (number)'
 'Threatened Species: Invertebrates (number)'
 'Threatened Species: Plants (number)'
 'Threatened Species: Total (number)']


" to show the unique values under the 'series' column "

In [ ]:
print(df2['Year'].unique())
print(df1['Year'].unique())
print(df3['Year'].unique())
print(df4['Year'].unique())

[2004 2010 2016 2017 2018 2019 2020]
[1975 1985 1995 2005 2010 2015 2016 2017]
[2005 2010 2017 2019]
[2005 2010 2017 2000]
